"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowRight, Check, ChevronRight, CircleUserRound, CreditCard, Heart, Menu, MessageCircle, Minus, PackageCheck, Plus, Search, ShieldCheck, ShoppingCart, Star, Tag, Truck, Wrench, X } from "lucide-react";

type Product = { id:number; name:string; category:"Ropa"|"Ferretería"|"Hogar"; price:number; oldPrice?:number; rating:number; image:string; badge?:string };
const PRODUCTS: Product[] = [
  {id:1,name:"Polo básico premium para hombre",category:"Ropa",price:39.90,oldPrice:59.90,rating:4.8,badge:"-33%",image:"https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=700&q=85"},
  {id:2,name:"Vestido casual de temporada",category:"Ropa",price:69.90,oldPrice:99.90,rating:4.7,badge:"Oferta",image:"https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=700&q=85"},
  {id:3,name:"Zapatillas urbanas unisex",category:"Ropa",price:119.90,oldPrice:159.90,rating:4.9,badge:"Top ventas",image:"https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=700&q=85"},
  {id:4,name:"Casaca denim clásica",category:"Ropa",price:109.90,oldPrice:149.90,rating:4.6,image:"https://images.unsplash.com/photo-1523205771623-e0faa4d2813d?auto=format&fit=crop&w=700&q=85"},
  {id:5,name:"Taladro percutor 650W",category:"Ferretería",price:179.90,oldPrice:229.90,rating:4.9,badge:"-22%",image:"https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=700&q=85"},
  {id:6,name:"Juego de herramientas 108 piezas",category:"Ferretería",price:249.90,oldPrice:329.90,rating:4.8,badge:"Más vendido",image:"https://images.unsplash.com/photo-1581147036324-c1c89c2c8b5c?auto=format&fit=crop&w=700&q=85"},
  {id:7,name:"Amoladora angular 4 1/2 pulgadas",category:"Ferretería",price:139.90,oldPrice:189.90,rating:4.7,image:"https://images.unsplash.com/photo-1572981779307-38b8cabb2407?auto=format&fit=crop&w=700&q=85"},
  {id:8,name:"Caja organizadora profesional",category:"Ferretería",price:89.90,rating:4.5,image:"https://images.unsplash.com/photo-1530124566582-a618bc2615dc?auto=format&fit=crop&w=700&q=85"},
  {id:9,name:"Set de sábanas algodón 2 plazas",category:"Hogar",price:79.90,oldPrice:119.90,rating:4.7,badge:"-33%",image:"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=700&q=85"},
  {id:10,name:"Lámpara de mesa nórdica",category:"Hogar",price:64.90,oldPrice:84.90,rating:4.8,image:"https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=700&q=85"},
  {id:11,name:"Organizador multiuso de 4 niveles",category:"Hogar",price:94.90,rating:4.6,image:"https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=700&q=85"},
  {id:12,name:"Set de cocina antiadherente",category:"Hogar",price:189.90,oldPrice:249.90,rating:4.9,badge:"Oferta",image:"https://images.unsplash.com/photo-1584990347449-a1d9f800a783?auto=format&fit=crop&w=700&q=85"},
];
const money=(n:number)=>`S/ ${n.toFixed(2)}`;

export default function Home(){
  const [menuOpen,setMenuOpen]=useState(false),[cartOpen,setCartOpen]=useState(false),[checkoutOpen,setCheckoutOpen]=useState(false);
  const [query,setQuery]=useState(""),[category,setCategory]=useState("Todos"),[favorites,setFavorites]=useState<number[]>([]);
  const [cart,setCart]=useState<Record<number,number>>({});
  const [hydrated,setHydrated]=useState(false);
  useEffect(()=>{try{setCart(JSON.parse(localStorage.getItem("cayo-cart")||"{}"));setFavorites(JSON.parse(localStorage.getItem("cayo-favorites")||"[]"))}catch{}finally{setHydrated(true)}},[]);
  useEffect(()=>{if(hydrated)localStorage.setItem("cayo-cart",JSON.stringify(cart))},[cart,hydrated]);
  useEffect(()=>{if(hydrated)localStorage.setItem("cayo-favorites",JSON.stringify(favorites))},[favorites,hydrated]);
  const filtered=useMemo(()=>PRODUCTS.filter(p=>(category==="Todos"||p.category===category)&&p.name.toLowerCase().includes(query.toLowerCase())),[category,query]);
  const items=PRODUCTS.filter(p=>cart[p.id]).map(p=>({...p,qty:cart[p.id]})),count=Object.values(cart).reduce((a,b)=>a+b,0),subtotal=items.reduce((s,p)=>s+p.price*p.qty,0);
  const add=(id:number)=>{setCart(c=>({...c,[id]:(c[id]||0)+1}));setCartOpen(true)};
  const change=(id:number,delta:number)=>setCart(c=>{const n={...c,[id]:(c[id]||0)+delta};if(n[id]<=0)delete n[id];return n});
  const goToCatalog=(cat:string)=>{setCategory(cat);setMenuOpen(false);document.getElementById("catalogo")?.scrollIntoView({behavior:"smooth"})};
  const whatsappOrder=()=>{const detail=items.map(p=>`• ${p.qty} x ${p.name} — ${money(p.price*p.qty)}`).join("%0A");window.open(`https://wa.me/51992110555?text=Hola%20Cayo,%20deseo%20realizar%20este%20pedido:%0A%0A${detail}%0A%0ATotal:%20${money(subtotal)}%0A%0AMis%20datos%20son:`,"_blank","noopener,noreferrer")};
  return <main>
    <div className="topbar"><span>Despachos a todo el Perú</span><span>Compra segura · Atención: 992 110 555</span></div>
    <header className="header"><div className="header-inner">
      <button className="mobile-menu" aria-label="Abrir menú" onClick={()=>setMenuOpen(!menuOpen)}><Menu/></button>
      <a className="logo" href="#inicio" aria-label="Cayo inicio"><span>C</span>AYO</a>
      <nav className={menuOpen?"nav open":"nav"}><button onClick={()=>goToCatalog("Todos")}>Categorías</button><button onClick={()=>goToCatalog("Ropa")}>Moda</button><button onClick={()=>goToCatalog("Ferretería")}>Ferretería</button><a href="#ofertas">Ofertas</a><a href="#beneficios">Beneficios</a></nav>
      <div className="search-wrap"><Search size={20}/><input value={query} onChange={e=>setQuery(e.target.value)} onFocus={()=>document.getElementById("catalogo")?.scrollIntoView({behavior:"smooth"})} placeholder="¿Qué estás buscando?" aria-label="Buscar productos"/></div>
      <button className="icon-btn user-btn" aria-label="Mi cuenta"><CircleUserRound/></button><button className="cart-btn" onClick={()=>setCartOpen(true)} aria-label={`Carrito con ${count} productos`}><ShoppingCart/><span>{count}</span></button>
    </div></header>
    <section id="inicio" className="hero"><div className="hero-copy"><span className="eyebrow">NUEVA TEMPORADA EN CAYO</span><h1>Todo lo que necesitas,<br/><em>en un solo lugar.</em></h1><p>Moda, herramientas y hogar con precios que sí convienen.</p><div className="hero-actions"><button className="primary" onClick={()=>goToCatalog("Todos")}>Comprar ahora <ArrowRight size={19}/></button><a className="secondary" href="#ofertas">Ver ofertas</a></div><div className="hero-proof"><span><Check/> Pago seguro</span><span><Check/> Envíos nacionales</span></div></div>
      <div className="hero-visual"><div className="hero-card fashion"><img src="https://images.unsplash.com/photo-1529518152792-d08317b26e22?auto=format&fit=crop&fm=jpg&q=85&w=1200" alt="Familia con ropa de temporada"/><span>MODA<br/><b>hasta -40%</b></span></div><div className="hero-card tools"><img src="https://images.unsplash.com/photo-1602052793312-b99c2a9ee797?auto=format&fit=crop&fm=jpg&q=85&w=900" alt="Herramientas de ferretería"/><span>FERRETERÍA<br/><b>precios bajos</b></span></div></div>
    </section>
    <section className="quick-cats" aria-label="Categorías principales"><button onClick={()=>goToCatalog("Ropa")}><div className="cat-icon coral">👕</div><span>Moda</span><small>Para todos</small></button><button onClick={()=>goToCatalog("Ferretería")}><div className="cat-icon blue"><Wrench/></div><span>Ferretería</span><small>Construye y repara</small></button><button onClick={()=>goToCatalog("Hogar")}><div className="cat-icon gold">🏠</div><span>Hogar</span><small>Renueva tus espacios</small></button><a href="#ofertas"><div className="cat-icon red"><Tag/></div><span>Liquidación</span><small>Últimas unidades</small></a></section>
    <section id="ofertas" className="offer-strip"><div><span>OFERTA DE LA SEMANA</span><h2>Renueva, repara y estrena</h2><p>Hasta 35% de descuento en productos seleccionados.</p></div><button onClick={()=>goToCatalog("Todos")}>Ver productos <ChevronRight/></button></section>
    <section id="catalogo" className="catalog section-pad"><div className="section-heading"><div><span className="eyebrow">NUESTROS PRODUCTOS</span><h2>Encuentra tu favorito</h2></div><span>{filtered.length} productos</span></div><div className="filters">{["Todos","Ropa","Ferretería","Hogar"].map(c=><button key={c} className={category===c?"active":""} onClick={()=>setCategory(c)}>{c}</button>)}</div>
      {filtered.length?<div className="product-grid">{filtered.map(product=><article className="product-card" key={product.id}><div className="product-image">{product.badge&&<span className="badge">{product.badge}</span>}<button className={favorites.includes(product.id)?"heart active":"heart"} onClick={()=>setFavorites(f=>f.includes(product.id)?f.filter(x=>x!==product.id):[...f,product.id])} aria-label="Agregar a favoritos"><Heart fill={favorites.includes(product.id)?"currentColor":"none"}/></button><img src={product.image} alt={product.name}/></div><div className="product-info"><small>{product.category}</small><h3>{product.name}</h3><div className="rating"><Star fill="currentColor"/> {product.rating} <span>(24)</span></div><div className="price"><b>{money(product.price)}</b>{product.oldPrice&&<del>{money(product.oldPrice)}</del>}</div><button className="add-btn" onClick={()=>add(product.id)}><ShoppingCart size={18}/> Agregar al carrito</button></div></article>)}</div>:<div className="empty"><Search/><h3>No encontramos productos</h3><p>Prueba con otra palabra o categoría.</p><button onClick={()=>{setQuery("");setCategory("Todos")}}>Ver todos</button></div>}
    </section>
    <section id="beneficios" className="benefits section-pad"><article><Truck/><div><h3>Envíos a todo el Perú</h3><p>Coordinamos una entrega rápida y segura.</p></div></article><article><ShieldCheck/><div><h3>Compra protegida</h3><p>Confirma todos los detalles antes de pagar.</p></div></article><article><CreditCard/><div><h3>Medios de pago</h3><p>Yape, Plin, transferencia y efectivo.</p></div></article><article><MessageCircle/><div><h3>Atención personalizada</h3><p>Escríbenos al 992 110 555.</p></div></article></section>
    <section className="newsletter section-pad"><div><span className="eyebrow">BENEFICIOS CAYO</span><h2>Entérate primero de nuestras ofertas</h2><p>Recibe promociones y nuevos productos.</p></div><form onSubmit={e=>{e.preventDefault();alert("¡Gracias! Pronto recibirás nuestras novedades.")}}><input type="email" required placeholder="Tu correo electrónico"/><button>Quiero recibir ofertas</button></form></section>
    <footer><div className="footer-grid"><div><a className="logo light" href="#inicio"><span>C</span>AYO</a><p>Tu tienda de confianza para vestir, renovar y construir.</p><a className="wa-link" href="https://wa.me/51992110555" target="_blank" rel="noreferrer"><MessageCircle/> 992 110 555</a></div><div><h3>Compra</h3><button onClick={()=>goToCatalog("Ropa")}>Moda</button><button onClick={()=>goToCatalog("Ferretería")}>Ferretería</button><button onClick={()=>goToCatalog("Hogar")}>Hogar</button><a href="#ofertas">Ofertas</a></div><div><h3>Ayuda</h3><a href="#beneficios">Despachos</a><a href="#beneficios">Medios de pago</a><a href="https://wa.me/51992110555">Cambios y devoluciones</a><a href="https://wa.me/51992110555">Contáctanos</a></div><div><h3>Horario de atención</h3><p>Lunes a sábado<br/>9:00 a. m. – 7:00 p. m.</p><p>Domingos<br/>10:00 a. m. – 3:00 p. m.</p></div></div><div className="footer-bottom"><span>© 2026 Cayo. Todos los derechos reservados.</span><span>Precios expresados en soles (S/).</span></div></footer>
    <a className="floating-wa" href="https://wa.me/51992110555?text=Hola%20Cayo,%20quiero%20información%20sobre%20sus%20productos" target="_blank" rel="noreferrer" aria-label="Escribir a Cayo por WhatsApp"><MessageCircle/><span>¿Necesitas ayuda?</span></a>
    {cartOpen&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setCartOpen(false)}}><aside className="cart-panel"><div className="cart-head"><div><ShoppingCart/><h2>Tu carrito</h2><span>{count} productos</span></div><button onClick={()=>setCartOpen(false)} aria-label="Cerrar carrito"><X/></button></div><div className="cart-content">{items.length?items.map(p=><div className="cart-item" key={p.id}><img src={p.image} alt=""/><div><small>{p.category}</small><h3>{p.name}</h3><b>{money(p.price)}</b><div className="qty"><button onClick={()=>change(p.id,-1)} aria-label="Restar"><Minus/></button><span>{p.qty}</span><button onClick={()=>change(p.id,1)} aria-label="Sumar"><Plus/></button></div></div><button className="remove" onClick={()=>setCart(c=>{const n={...c};delete n[p.id];return n})} aria-label="Eliminar"><X/></button></div>):<div className="cart-empty"><ShoppingCart/><h3>Tu carrito está vacío</h3><p>Agrega productos para comenzar tu compra.</p><button onClick={()=>{setCartOpen(false);goToCatalog("Todos")}}>Ver productos</button></div>}</div>{items.length>0&&<div className="cart-summary"><div><span>Subtotal</span><b>{money(subtotal)}</b></div><small>El costo de envío se coordina por WhatsApp.</small><button onClick={()=>{setCartOpen(false);setCheckoutOpen(true)}}>Continuar compra <ArrowRight/></button><button className="continue" onClick={()=>setCartOpen(false)}>Seguir comprando</button></div>}</aside></div>}
    {checkoutOpen&&<div className="overlay center"><div className="checkout"><button className="modal-close" onClick={()=>setCheckoutOpen(false)}><X/></button><div className="checkout-icon"><PackageCheck/></div><h2>Finaliza tu pedido</h2><p>Tu compra se enviará a nuestro WhatsApp para confirmar disponibilidad, dirección y medio de pago.</p><div className="order-box"><span>{count} productos</span><b>Total: {money(subtotal)}</b></div><button className="whatsapp-checkout" onClick={whatsappOrder}><MessageCircle/> Pedir por WhatsApp</button><small>No se realizará ningún cobro automático.</small></div></div>}
  </main>
}
